import type { Armor, BuyId, StructKind, UnitKind } from "./types";

export interface Vs {
  light: number;
  armor: number;
  air: number;
  structure: number;
}

export interface UnitDef {
  id: UnitKind;
  name: string;
  cost: number;
  hp: number;
  move: number;
  minRange: number;
  maxRange: number;
  vision: number;
  atk: number;
  vs: Vs;
  armor: Armor;
  domain: "ground" | "air" | "sea";
  /** Ground: can ford water. Air: false means it cannot cross water. */
  water?: boolean;
  indirect: boolean;
  capture: boolean;
  repair: number;
  /** Shots per turn. Defaults to 1. */
  shots?: number;
  /** Manhattan blip radius. Weapons stay at 1. */
  radar?: number;
  /** Turns after you pay before it can act. */
  build?: number;
  /** Mines this unit carries. */
  mines?: number;
  blurb: string;
}

export interface StructDef {
  id: StructKind;
  name: string;
  cost: number;
  hp: number;
  minRange: number;
  maxRange: number;
  vision: number;
  radar: number;
  atk: number;
  vs: Vs;
  dr: number;
  income: number;
  blocks: boolean;
  property: boolean;
  /** Shots per turn. Defaults to 1. */
  shots?: number;
  /** Turns after you pay before it can act. */
  build?: number;
  blurb: string;
}

const NONE: Vs = { light: 0, armor: 0, air: 0, structure: 0 };

export const UNITS: UnitDef[] = [
  {
    id: "squad",
    name: "Infantry",
    cost: 140,
    build: 1,
    hp: 8,
    move: 15,
    minRange: 1,
    maxRange: 2,
    vision: 2,
    atk: 4,
    vs: { light: 1.2, armor: 0.2, air: 0.05, structure: 0.35 },
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: true,
    repair: 0,
    shots: 2,
    blurb: "Rifle squad. Short range, two shots. Hurts troops, barely scratches armor. Captures bases.",
  },
  {
    id: "marksman",
    name: "Sniper",
    cost: 220,
    build: 1,
    hp: 6,
    move: 12,
    minRange: 2,
    maxRange: 8,
    vision: 3,
    atk: 7,
    vs: { light: 1.7, armor: 0.2, air: 0.05, structure: 0.2 },
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: true,
    repair: 0,
    blurb: "Long rifle, range 2–8. One careful shot. Lethal to troops, useless against tanks. Can capture.",
  },
  {
    id: "bullhead",
    name: "IFV",
    cost: 480,
    build: 2,
    hp: 14,
    move: 16,
    minRange: 1,
    maxRange: 3,
    vision: 2,
    atk: 6,
    vs: { light: 1.35, armor: 0.55, air: 0.15, structure: 0.7 },
    armor: "armor",
    domain: "ground",
    water: true,
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    shots: 2,
    blurb: "Autocannon, two shots, faster than a tank. It can cross water. Strong against troops, weak against a real tank. Radar 1.",
  },
  {
    id: "tank",
    name: "Tank",
    cost: 720,
    build: 2,
    hp: 22,
    move: 12,
    minRange: 1,
    maxRange: 4,
    vision: 1,
    atk: 10,
    vs: { light: 1.05, armor: 1.45, air: 0, structure: 1.25 },
    armor: "armor",
    domain: "ground",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "Main gun, one shot. Hard on tanks and buildings. Cannot hit aircraft. Radar 1.",
  },
  {
    id: "pike",
    name: "Anti-Tank",
    cost: 420,
    build: 2,
    hp: 10,
    move: 10,
    minRange: 2,
    maxRange: 5,
    vision: 1,
    atk: 9,
    vs: { light: 0.4, armor: 1.85, air: 0, structure: 0.7 },
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "Missile team. Deadly to armor from range 2–5. Poor against troops. Radar 1.",
  },
  {
    id: "aagun",
    name: "Mobile AA",
    cost: 400,
    build: 2,
    hp: 10,
    move: 12,
    minRange: 1,
    maxRange: 6,
    vision: 1,
    atk: 7,
    vs: { light: 0.35, armor: 0.15, air: 1.75, structure: 0.1 },
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    shots: 2,
    blurb: "Truck-mounted anti-air. Two shots, range 6. Built to kill aircraft, little use on the ground. Radar 1.",
  },
  {
    id: "lobber",
    name: "Mortar",
    cost: 300,
    build: 1,
    hp: 8,
    move: 8,
    minRange: 3,
    maxRange: 7,
    vision: 1,
    atk: 7,
    vs: { light: 1.25, armor: 0.7, air: 0, structure: 1.15 },
    armor: "light",
    domain: "ground",
    indirect: true,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "Indirect fire, range 3–7. Inaccurate. Good against troops and light cover. Cannot hit aircraft. Radar 1.",
  },
  {
    id: "rotor",
    name: "Helicopter",
    cost: 680,
    build: 2,
    hp: 11,
    move: 18,
    minRange: 1,
    maxRange: 4,
    vision: 1,
    atk: 7,
    vs: { light: 1.3, armor: 0.65, air: 0.45, structure: 0.45 },
    armor: "air",
    domain: "air",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    shots: 2,
    blurb: "Gunship. Two shots. Flies over walls and water. Fighters and anti-air kill it. Radar 1.",
  },
  {
    id: "fighter",
    name: "Fighter",
    cost: 780,
    build: 2,
    hp: 10,
    move: 20,
    minRange: 1,
    maxRange: 5,
    vision: 1,
    atk: 8,
    vs: { light: 0.35, armor: 0.15, air: 1.85, structure: 0.1 },
    armor: "air",
    domain: "air",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    shots: 2,
    blurb: "Fastest thing in the sky. Two shots. Owns other aircraft. Weak against ground targets. Radar 1.",
  },
  {
    id: "bomber",
    name: "Bomber",
    cost: 860,
    build: 2,
    hp: 14,
    move: 16,
    minRange: 1,
    maxRange: 3,
    vision: 1,
    atk: 11,
    vs: { light: 1.2, armor: 1.25, air: 0, structure: 1.75 },
    armor: "air",
    domain: "air",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "One bomb run, range 3. Wrecks buildings and armor. Cannot dogfight. Radar 1.",
  },
  {
    id: "tender",
    name: "Medevac",
    cost: 340,
    build: 1,
    hp: 9,
    move: 18,
    minRange: 0,
    maxRange: 0,
    vision: 3,
    atk: 0,
    vs: NONE,
    armor: "air",
    domain: "air",
    indirect: false,
    capture: false,
    repair: 4,
    blurb: "Unarmed helicopter. Heals 4 on a friendly within 2 squares. Click them, or press Heal. It flies over water, and it cannot heal while it is still being built.",
  },
  {
    id: "ship",
    name: "Cruiser",
    cost: 980,
    build: 2,
    hp: 28,
    move: 12,
    minRange: 3,
    maxRange: 8,
    vision: 1,
    atk: 11,
    vs: { light: 0.9, armor: 1.15, air: 0.2, structure: 1.5 },
    armor: "armor",
    domain: "sea",
    indirect: true,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "Heavy guns, range 3–8. Shells ships and the shore. Slow. A destroyer inside minimum range is safe. Radar 1.",
  },
  {
    id: "destroyer",
    name: "Destroyer",
    cost: 760,
    build: 2,
    hp: 18,
    move: 14,
    minRange: 1,
    maxRange: 5,
    vision: 1,
    atk: 8,
    vs: { light: 0.55, armor: 1.4, air: 1.05, structure: 0.45 },
    armor: "armor",
    domain: "sea",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    shots: 2,
    blurb: "Fast escort. Two shots. Hunts cruisers and can engage aircraft. Weak against fortifications. Radar 1.",
  },
  {
    id: "ram",
    name: "Howitzer",
    cost: 640,
    build: 2,
    hp: 12,
    move: 8,
    minRange: 3,
    maxRange: 8,
    vision: 1,
    atk: 10,
    vs: { light: 0.9, armor: 1.05, air: 0, structure: 1.65 },
    armor: "light",
    domain: "ground",
    indirect: true,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "Siege gun, range 3–8. Inaccurate, hard on headquarters. Slow and fragile. Radar 1.",
  },
  {
    id: "layer",
    name: "Minelayer",
    cost: 280,
    build: 2,
    hp: 10,
    move: 10,
    minRange: 0,
    maxRange: 0,
    vision: 2,
    atk: 0,
    vs: NONE,
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    mines: 4,
    blurb: "Lays a hidden mine on an adjacent ground square. Carries 4. Restock beside your Headquarters or a Supply Base, 70 each. Unarmed. Radar 1.",
  },
  {
    id: "dish",
    name: "Portable Radar",
    cost: 500,
    build: 2,
    hp: 9,
    move: 9,
    minRange: 0,
    maxRange: 0,
    vision: 2,
    atk: 0,
    vs: NONE,
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 5,
    blurb: "Radar truck. Same 5-tile radar as a tower, and you can drive it forward. Unarmed. Ridges still block it.",
  },
  {
    id: "salvo",
    name: "Rocket Battery",
    cost: 780,
    build: 2,
    hp: 12,
    move: 8,
    minRange: 4,
    maxRange: 9,
    vision: 1,
    atk: 7,
    vs: { light: 1.2, armor: 0.95, air: 0, structure: 1.45 },
    armor: "light",
    domain: "ground",
    indirect: true,
    capture: false,
    repair: 0,
    radar: 1,
    shots: 3,
    blurb: "Three rockets, range 4–9. A full salvo outdamages a mortar. Inaccurate, and it cannot hit aircraft. Two turns to build.",
  },
  {
    id: "heavy",
    name: "Heavy Tank",
    cost: 1100,
    build: 2,
    hp: 34,
    move: 9,
    minRange: 1,
    maxRange: 4,
    vision: 1,
    atk: 14,
    vs: { light: 1.15, armor: 1.65, air: 0, structure: 1.55 },
    armor: "armor",
    domain: "ground",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "The tank, but worse to face. More health, a harder gun, same range. Still cannot hit aircraft. Two turns to build.",
  },
  {
    id: "sam",
    name: "SAM",
    cost: 680,
    build: 1,
    hp: 12,
    move: 10,
    minRange: 2,
    maxRange: 8,
    vision: 2,
    atk: 13,
    vs: { light: 0.2, armor: 0.1, air: 2.2, structure: 0.05 },
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 3,
    blurb: "One missile, range 2–8, ready in one turn. Kills aircraft farther out than a mobile AA gun, and it sees farther. Weak against ground.",
  },
  {
    id: "drone",
    name: "Recon Drone",
    cost: 520,
    build: 1,
    hp: 7,
    move: 24,
    minRange: 1,
    maxRange: 3,
    vision: 3,
    atk: 4,
    vs: { light: 1, armor: 0.2, air: 0.35, structure: 0.2 },
    armor: "air",
    domain: "air",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 5,
    blurb: "Ready in one turn. Radar 5 and the longest move in the air. The gun can drop infantry. Fighters and SAMs still delete it.",
  },
  {
    id: "sub",
    name: "Submarine",
    cost: 900,
    build: 2,
    hp: 16,
    move: 14,
    minRange: 1,
    maxRange: 5,
    vision: 2,
    atk: 14,
    vs: { light: 0.35, armor: 1.85, air: 0, structure: 0.4 },
    armor: "armor",
    domain: "sea",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "Better at sinking ships than a destroyer, including inside a cruiser's minimum range. Cannot hit aircraft. Two turns to build.",
  },
  {
    id: "mg",
    name: "Machine Gun Team",
    cost: 540,
    build: 1,
    hp: 11,
    move: 11,
    minRange: 1,
    maxRange: 4,
    vision: 2,
    atk: 5,
    vs: { light: 1.55, armor: 0.3, air: 0.1, structure: 0.25 },
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: true,
    repair: 0,
    radar: 1,
    shots: 3,
    blurb: "Three shots, range 4, ready in one turn. Better against troops than a sniper, and it can still capture. Radar 1.",
  },
  {
    id: "ranger",
    name: "Ranger",
    cost: 680,
    build: 1,
    hp: 13,
    move: 16,
    minRange: 1,
    maxRange: 4,
    vision: 3,
    atk: 6,
    vs: { light: 1.45, armor: 0.55, air: 0.1, structure: 0.45 },
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: true,
    repair: 0,
    radar: 1,
    shots: 2,
    blurb: "The infantry line's finish. Faster and tougher than a rifle squad, range 4, and it captures. Ready in one turn. Radar 1.",
  },
  {
    id: "breaker",
    name: "Assault Gun",
    cost: 1280,
    build: 2,
    hp: 26,
    move: 10,
    minRange: 1,
    maxRange: 5,
    vision: 1,
    atk: 16,
    vs: { light: 1.05, armor: 1.4, air: 0, structure: 1.9 },
    armor: "armor",
    domain: "ground",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "One gun, range 5. Hits buildings harder than a heavy tank and reaches a square farther. Cannot hit aircraft. Radar 1.",
  },
  {
    id: "guard",
    name: "Guard Tank",
    cost: 1540,
    build: 2,
    hp: 42,
    move: 9,
    minRange: 1,
    maxRange: 4,
    vision: 1,
    atk: 16,
    vs: { light: 1.2, armor: 1.8, air: 0, structure: 1.65 },
    armor: "armor",
    domain: "ground",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "More health and a harder gun than the heavy tank. Same range. Still cannot hit aircraft. Two turns. Radar 1.",
  },
  {
    id: "battery",
    name: "Battleship",
    cost: 1480,
    build: 2,
    hp: 38,
    move: 10,
    minRange: 3,
    maxRange: 10,
    vision: 1,
    atk: 15,
    vs: { light: 1, armor: 1.35, air: 0.15, structure: 1.9 },
    armor: "armor",
    domain: "sea",
    indirect: true,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "Shore guns, range 3–10. Outranges a cruiser and hits buildings harder. Slow. A ship inside minimum range is safe. Radar 1.",
  },
  {
    id: "frigate",
    name: "Frigate",
    cost: 1120,
    build: 2,
    hp: 20,
    move: 16,
    minRange: 1,
    maxRange: 6,
    vision: 1,
    atk: 9,
    vs: { light: 0.6, armor: 1.25, air: 1.45, structure: 0.5 },
    armor: "armor",
    domain: "sea",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    shots: 2,
    blurb: "Faster than a destroyer, two shots, range 6. Better against aircraft and still hunts ships. Radar 1.",
  },
  {
    id: "strike",
    name: "Strike Jet",
    cost: 1240,
    build: 2,
    hp: 13,
    move: 22,
    minRange: 1,
    maxRange: 5,
    vision: 1,
    atk: 12,
    vs: { light: 1.15, armor: 1.2, air: 1.15, structure: 1.55 },
    armor: "air",
    domain: "air",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    shots: 2,
    blurb: "Two bombs, range 5, faster than a bomber, and it can fight back in the air. Harder on buildings than a fighter. Radar 1.",
  },
  {
    id: "lance",
    name: "Interceptor",
    cost: 1180,
    build: 2,
    hp: 12,
    move: 24,
    minRange: 1,
    maxRange: 6,
    vision: 1,
    atk: 11,
    vs: { light: 0.4, armor: 0.2, air: 2.15, structure: 0.15 },
    armor: "air",
    domain: "air",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    shots: 2,
    blurb: "Faster than a fighter, range 6, two shots, and it kills aircraft harder. Weak on the ground. The Ace goes further. Radar 1.",
  },
  {
    id: "spotter",
    name: "Spotter",
    cost: 260,
    build: 1,
    hp: 7,
    move: 14,
    minRange: 2,
    maxRange: 6,
    vision: 4,
    atk: 5,
    vs: { light: 1.4, armor: 0.25, air: 0.05, structure: 0.2 },
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: true,
    repair: 0,
    radar: 2,
    blurb: "Marks troops from range 6 and can capture. Sees farther than a sniper. Radar 2. Ready in one turn.",
  },
  {
    id: "grenade",
    name: "Grenadier",
    cost: 360,
    build: 1,
    hp: 10,
    move: 12,
    minRange: 1,
    maxRange: 2,
    vision: 2,
    atk: 8,
    vs: { light: 1.5, armor: 0.45, air: 0, structure: 1.2 },
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: true,
    repair: 0,
    radar: 1,
    blurb: "Close range, one bomb. Hurts troops and buildings, and it can capture. Ready in one turn. Radar 1.",
  },
  {
    id: "scorch",
    name: "Flamethrower",
    cost: 520,
    build: 1,
    hp: 12,
    move: 11,
    minRange: 1,
    maxRange: 2,
    vision: 2,
    atk: 9,
    vs: { light: 1.9, armor: 0.35, air: 0, structure: 1.05 },
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    shots: 2,
    blurb: "Two close shots. Better against troops than a grenadier. Cannot capture. Ready in one turn. Radar 1.",
  },
  {
    id: "field",
    name: "Field Gun",
    cost: 560,
    build: 2,
    hp: 10,
    move: 8,
    minRange: 2,
    maxRange: 7,
    vision: 1,
    atk: 9,
    vs: { light: 1.1, armor: 0.95, air: 0, structure: 1.4 },
    armor: "light",
    domain: "ground",
    indirect: true,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "Indirect gun, range 2–7. A step past the mortar against buildings. Cannot hit aircraft. Radar 1.",
  },
  {
    id: "siege",
    name: "Siege Mortar",
    cost: 980,
    build: 2,
    hp: 12,
    move: 7,
    minRange: 4,
    maxRange: 11,
    vision: 1,
    atk: 13,
    vs: { light: 1, armor: 1.15, air: 0, structure: 1.85 },
    armor: "light",
    domain: "ground",
    indirect: true,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "The long mortar. Range 4–11. Harder on buildings than a rocket battery. Inaccurate. Cannot hit aircraft. Radar 1.",
  },
  {
    id: "sapper",
    name: "Sapper",
    cost: 640,
    build: 1,
    hp: 14,
    move: 13,
    minRange: 1,
    maxRange: 3,
    vision: 2,
    atk: 7,
    vs: { light: 1.3, armor: 0.7, air: 0, structure: 1.45 },
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: true,
    repair: 0,
    radar: 1,
    shots: 2,
    blurb: "The infantry finish for buildings. Two shots, range 3, captures, and it cracks cover better than a ranger. Ready in one turn. Radar 1.",
  },
  {
    id: "scout",
    name: "Scout Car",
    cost: 440,
    build: 1,
    hp: 12,
    move: 20,
    minRange: 1,
    maxRange: 3,
    vision: 3,
    atk: 6,
    vs: { light: 1.25, armor: 0.4, air: 0.1, structure: 0.4 },
    armor: "armor",
    domain: "ground",
    water: true,
    indirect: false,
    capture: false,
    repair: 0,
    radar: 2,
    shots: 2,
    blurb: "Fast armor. Two shots, radar 2. It can cross water. Better at finding the enemy than fighting a tank. Ready in one turn.",
  },
  {
    id: "hunter",
    name: "Tank Hunter",
    cost: 860,
    build: 2,
    hp: 14,
    move: 12,
    minRange: 2,
    maxRange: 6,
    vision: 1,
    atk: 12,
    vs: { light: 0.45, armor: 2.05, air: 0, structure: 0.8 },
    armor: "armor",
    domain: "ground",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "Gun built for tanks, range 2–6. Hits armor harder than a normal tank. Poor against troops. Cannot hit aircraft. Radar 1.",
  },
  {
    id: "wrecker",
    name: "Siege Tank",
    cost: 1680,
    build: 2,
    hp: 28,
    move: 8,
    minRange: 1,
    maxRange: 6,
    vision: 1,
    atk: 18,
    vs: { light: 1.1, armor: 1.5, air: 0, structure: 2.15 },
    armor: "armor",
    domain: "ground",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "Past the assault gun. Range 6, one huge shot, and it wrecks buildings. Cannot hit aircraft. Radar 1.",
  },
  {
    id: "monarch",
    name: "Breakthrough Tank",
    cost: 1900,
    build: 2,
    hp: 50,
    move: 8,
    minRange: 1,
    maxRange: 5,
    vision: 1,
    atk: 18,
    vs: { light: 1.25, armor: 1.95, air: 0, structure: 1.8 },
    armor: "armor",
    domain: "ground",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "Past the guard tank. More health, a harder gun, and one more square of range. Still cannot hit aircraft. Radar 1.",
  },
  {
    id: "raider",
    name: "Gunboat",
    cost: 640,
    build: 1,
    hp: 16,
    move: 18,
    minRange: 1,
    maxRange: 4,
    vision: 1,
    atk: 8,
    vs: { light: 0.9, armor: 1.05, air: 0.45, structure: 0.4 },
    armor: "armor",
    domain: "sea",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    shots: 2,
    blurb: "Small fast boat. Two shots, range 4, ready in one turn. Weaker than a destroyer, but it gets into the fight sooner. Radar 1.",
  },
  {
    id: "lancer",
    name: "Missile Boat",
    cost: 1280,
    build: 2,
    hp: 18,
    move: 15,
    minRange: 3,
    maxRange: 8,
    vision: 1,
    atk: 11,
    vs: { light: 0.7, armor: 1.5, air: 0.85, structure: 0.75 },
    armor: "armor",
    domain: "sea",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    shots: 2,
    blurb: "Past the frigate. Two missiles, range 3–8. Better at ships and still bothers aircraft. Radar 1.",
  },
  {
    id: "lurker",
    name: "Hunter Sub",
    cost: 1320,
    build: 2,
    hp: 18,
    move: 15,
    minRange: 1,
    maxRange: 6,
    vision: 2,
    atk: 16,
    vs: { light: 0.3, armor: 2.15, air: 0, structure: 0.5 },
    armor: "armor",
    domain: "sea",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "Past the submarine. Range 6 and a harder torpedo. Still cannot hit aircraft. Radar 1.",
  },
  {
    id: "dread",
    name: "Dreadnought",
    cost: 1860,
    build: 2,
    hp: 46,
    move: 9,
    minRange: 4,
    maxRange: 12,
    vision: 1,
    atk: 17,
    vs: { light: 1, armor: 1.45, air: 0.2, structure: 2.1 },
    armor: "armor",
    domain: "sea",
    indirect: true,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "Past the battleship. Range 4–12. The longest shore gun. A ship inside minimum range is safe. Radar 1.",
  },
  {
    id: "thunder",
    name: "Attack Heli",
    cost: 980,
    build: 2,
    hp: 16,
    move: 18,
    minRange: 1,
    maxRange: 5,
    vision: 1,
    atk: 10,
    vs: { light: 1.4, armor: 1.1, air: 0.55, structure: 0.75 },
    armor: "air",
    domain: "air",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    shots: 2,
    blurb: "Heavier than the starter helicopter. Two shots, range 5, and it hurts armor. It flies over water. Fighters and SAMs still kill it. Radar 1.",
  },
  {
    id: "eye",
    name: "Scout Plane",
    cost: 740,
    build: 1,
    hp: 8,
    move: 26,
    minRange: 1,
    maxRange: 3,
    vision: 4,
    atk: 4,
    vs: { light: 0.8, armor: 0.15, air: 0.4, structure: 0.15 },
    armor: "air",
    domain: "air",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 6,
    blurb: "Past the drone. Radar 6, the longest move in the air, ready in one turn. The gun only bothers troops.",
  },
  {
    id: "vault",
    name: "Heavy Bomber",
    cost: 1560,
    build: 2,
    hp: 18,
    move: 15,
    minRange: 1,
    maxRange: 4,
    vision: 1,
    atk: 16,
    vs: { light: 1.3, armor: 1.45, air: 0, structure: 2.2 },
    armor: "air",
    domain: "air",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "Past the strike jet. One heavier bomb, range 4. The hardest building hit in the air. Cannot dogfight. Radar 1.",
  },
  {
    id: "ace",
    name: "Air Superiority",
    cost: 1420,
    build: 2,
    hp: 13,
    move: 26,
    minRange: 1,
    maxRange: 7,
    vision: 1,
    atk: 12,
    vs: { light: 0.35, armor: 0.2, air: 2.4, structure: 0.15 },
    armor: "air",
    domain: "air",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    shots: 2,
    blurb: "Past the interceptor. Range 7, two shots, and the hardest aircraft killer. Weak on the ground. Radar 1.",
  },
  {
    id: "breacher",
    name: "Breacher",
    cost: 640,
    build: 1,
    hp: 14,
    move: 12,
    minRange: 1,
    maxRange: 2,
    vision: 2,
    atk: 11,
    vs: { light: 1.4, armor: 0.55, air: 0, structure: 1.7 },
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: true,
    repair: 0,
    radar: 1,
    shots: 2,
    blurb: "Past the flamethrower. Two close shots that open buildings, and it can capture. Ready in one turn. Radar 1.",
  },
  {
    id: "demo",
    name: "Demolition Team",
    cost: 700,
    build: 1,
    hp: 12,
    move: 11,
    minRange: 1,
    maxRange: 2,
    vision: 2,
    atk: 8,
    vs: { light: 1.1, armor: 0.4, air: 0, structure: 1.9 },
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: true,
    repair: 0,
    radar: 1,
    mines: 3,
    blurb: "The other fork after the flamethrower. Carries 3 mines and cracks buildings. Can capture. Ready in one turn. Radar 1.",
  },
  {
    id: "pioneer",
    name: "Pioneer",
    cost: 720,
    build: 1,
    hp: 15,
    move: 14,
    minRange: 1,
    maxRange: 3,
    vision: 2,
    atk: 7,
    vs: { light: 1.2, armor: 0.65, air: 0, structure: 1.3 },
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: true,
    repair: 0,
    radar: 1,
    mines: 4,
    blurb: "Past the sapper. Carries 4 mines, captures, and moves faster. The gun is not the point. Ready in one turn. Radar 1.",
  },
  {
    id: "engineer",
    name: "Combat Engineer",
    cost: 760,
    build: 1,
    hp: 16,
    move: 12,
    minRange: 1,
    maxRange: 2,
    vision: 2,
    atk: 5,
    vs: { light: 1, armor: 0.35, air: 0, structure: 0.8 },
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: true,
    repair: 6,
    radar: 1,
    blurb: "The other fork after the sapper. Heals a friendly unit and can capture. Short gun. Ready in one turn. Radar 1.",
  },
  {
    id: "atgm",
    name: "Missile Team",
    cost: 980,
    build: 2,
    hp: 12,
    move: 10,
    minRange: 3,
    maxRange: 7,
    vision: 1,
    atk: 13,
    vs: { light: 0.4, armor: 2.35, air: 0.15, structure: 0.7 },
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "Past the tank hunter. Missiles from range 3–7. Harder on tanks than the hunter. Weak if the enemy is on top of it. Radar 1.",
  },
  {
    id: "ambush",
    name: "Ambush Gun",
    cost: 1040,
    build: 2,
    hp: 18,
    move: 9,
    minRange: 2,
    maxRange: 5,
    vision: 1,
    atk: 15,
    vs: { light: 0.55, armor: 2.25, air: 0, structure: 0.9 },
    armor: "armor",
    domain: "ground",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "The other fork after the tank hunter. A heavier gun at range 2–5. More health, less reach than the missile team. Radar 1.",
  },
  {
    id: "dozer",
    name: "Assault Dozer",
    cost: 1860,
    build: 2,
    hp: 38,
    move: 8,
    minRange: 1,
    maxRange: 2,
    vision: 1,
    atk: 14,
    vs: { light: 1.2, armor: 1.1, air: 0, structure: 2.5 },
    armor: "armor",
    domain: "ground",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    shots: 2,
    blurb: "Past the siege tank. Two short shots and the hardest building hit on tracks. It walks into the wall. Radar 1.",
  },
  {
    id: "spg",
    name: "Self-Propelled Gun",
    cost: 1920,
    build: 2,
    hp: 22,
    move: 8,
    minRange: 3,
    maxRange: 9,
    vision: 1,
    atk: 16,
    vs: { light: 1, armor: 1.35, air: 0, structure: 2.35 },
    armor: "armor",
    domain: "ground",
    indirect: true,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "The other fork after the siege tank. Indirect, range 3–9. Hits buildings harder than a howitzer and can still move. Radar 1.",
  },
  {
    id: "command",
    name: "Command Tank",
    cost: 2100,
    build: 2,
    hp: 42,
    move: 9,
    minRange: 1,
    maxRange: 5,
    vision: 2,
    atk: 16,
    vs: { light: 1.15, armor: 1.7, air: 0, structure: 1.4 },
    armor: "armor",
    domain: "ground",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 3,
    blurb: "Past the breakthrough tank. The gun is a step down. Radar 3 and vision 2 so the rest of the line can see. Radar names contacts inside it.",
  },
  {
    id: "spear",
    name: "Spearhead Tank",
    cost: 2300,
    build: 2,
    hp: 58,
    move: 9,
    minRange: 1,
    maxRange: 6,
    vision: 1,
    atk: 20,
    vs: { light: 1.3, armor: 2.15, air: 0, structure: 1.9 },
    armor: "armor",
    domain: "ground",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "The other fork after the breakthrough tank. More health, range 6, and a harder gun. Same build time. Cannot hit aircraft. Radar 1.",
  },
  {
    id: "monitor",
    name: "Monitor",
    cost: 1980,
    build: 2,
    hp: 40,
    move: 7,
    minRange: 2,
    maxRange: 8,
    vision: 1,
    atk: 20,
    vs: { light: 1.05, armor: 1.35, air: 0.1, structure: 2.4 },
    armor: "armor",
    domain: "sea",
    indirect: true,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "Past the dreadnought. A shorter, heavier shore gun, range 2–8. Better on buildings. Slow. Radar 1.",
  },
  {
    id: "battle",
    name: "Battlecruiser",
    cost: 2100,
    build: 2,
    hp: 40,
    move: 12,
    minRange: 3,
    maxRange: 10,
    vision: 1,
    atk: 16,
    vs: { light: 0.95, armor: 1.6, air: 0.35, structure: 1.7 },
    armor: "armor",
    domain: "sea",
    indirect: true,
    capture: false,
    repair: 0,
    radar: 1,
    shots: 2,
    blurb: "The other fork after the dreadnought. Faster, two shots, range 3–10. Less raw building damage, better at ships. Radar 1.",
  },
  {
    id: "asw",
    name: "Sub Hunter",
    cost: 1380,
    build: 1,
    hp: 20,
    move: 16,
    minRange: 1,
    maxRange: 6,
    vision: 3,
    atk: 12,
    vs: { light: 0.4, armor: 1.9, air: 0.4, structure: 0.4 },
    armor: "armor",
    domain: "sea",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 2,
    shots: 2,
    blurb: "Past the missile boat. Built to find and kill submarines. Two shots, vision 3, radar 2. Ready in one turn.",
  },
  {
    id: "escort",
    name: "Escort",
    cost: 1460,
    build: 2,
    hp: 22,
    move: 16,
    minRange: 1,
    maxRange: 7,
    vision: 2,
    atk: 10,
    vs: { light: 0.5, armor: 0.8, air: 1.6, structure: 0.35 },
    armor: "armor",
    domain: "sea",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 2,
    shots: 2,
    blurb: "The other fork after the missile boat. A ship's anti-air. Two shots, range 7, radar 2. Weak against a battleship.",
  },
  {
    id: "cruise",
    name: "Cruise Sub",
    cost: 1680,
    build: 2,
    hp: 18,
    move: 13,
    minRange: 4,
    maxRange: 11,
    vision: 1,
    atk: 15,
    vs: { light: 0.5, armor: 1.3, air: 0, structure: 1.7 },
    armor: "armor",
    domain: "sea",
    indirect: true,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "Past the hunter sub. Missiles at range 4–11. Hits the shore, not aircraft. A ship inside minimum range is safe. Radar 1.",
  },
  {
    id: "wolf",
    name: "Attack Sub",
    cost: 1600,
    build: 2,
    hp: 20,
    move: 17,
    minRange: 1,
    maxRange: 6,
    vision: 2,
    atk: 18,
    vs: { light: 0.25, armor: 2.4, air: 0, structure: 0.45 },
    armor: "armor",
    domain: "sea",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "The other fork after the hunter sub. Faster, and the torpedo hits ships harder. Still cannot hit aircraft. Radar 1.",
  },
  {
    id: "armed",
    name: "Armed Drone",
    cost: 860,
    build: 1,
    hp: 8,
    move: 20,
    minRange: 1,
    maxRange: 4,
    vision: 2,
    atk: 8,
    vs: { light: 1.2, armor: 0.7, air: 0.2, structure: 0.6 },
    armor: "air",
    domain: "air",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 2,
    shots: 2,
    blurb: "Past the scout plane. Two light shots, range 4, radar 2. Cheap and fragile. Ready in one turn. It flies over water.",
  },
  {
    id: "radarplane",
    name: "Radar Plane",
    cost: 900,
    build: 1,
    hp: 10,
    move: 24,
    minRange: 0,
    maxRange: 0,
    vision: 3,
    atk: 0,
    vs: NONE,
    armor: "air",
    domain: "air",
    water: true,
    indirect: false,
    capture: false,
    repair: 0,
    radar: 5,
    blurb: "The other fork after the scout plane. No gun. Radar 5 and it can cross water. Ready in one turn. Fighters still eat it.",
  },
  {
    id: "night",
    name: "Night Fighter",
    cost: 1560,
    build: 2,
    hp: 14,
    move: 24,
    minRange: 1,
    maxRange: 8,
    vision: 2,
    atk: 13,
    vs: { light: 0.4, armor: 0.25, air: 2.6, structure: 0.15 },
    armor: "air",
    domain: "air",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 2,
    shots: 2,
    blurb: "Past air superiority. Range 8, radar 2, two shots. Better at finding aircraft in the dark. Still weak on the ground.",
  },
  {
    id: "dogfight",
    name: "Dogfighter",
    cost: 1640,
    build: 2,
    hp: 14,
    move: 28,
    minRange: 1,
    maxRange: 6,
    vision: 1,
    atk: 14,
    vs: { light: 0.3, armor: 0.15, air: 2.7, structure: 0.1 },
    armor: "air",
    domain: "air",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    shots: 2,
    blurb: "The other fork after air superiority. The fastest plane and the hardest dogfight gun. Short range for a jet. Radar 1.",
  },
  {
    id: "strategic",
    name: "Strategic Bomber",
    cost: 2100,
    build: 2,
    hp: 20,
    move: 14,
    minRange: 2,
    maxRange: 5,
    vision: 1,
    atk: 18,
    vs: { light: 1.35, armor: 1.55, air: 0, structure: 2.5 },
    armor: "air",
    domain: "air",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "Past the heavy bomber. Same build time, a harder bomb, range 5. The best building hit in the air. Cannot dogfight. Radar 1.",
  },
  {
    id: "pathfinder",
    name: "Pathfinder",
    cost: 1760,
    build: 2,
    hp: 16,
    move: 18,
    minRange: 1,
    maxRange: 4,
    vision: 2,
    atk: 14,
    vs: { light: 1.15, armor: 1.2, air: 0, structure: 1.9 },
    armor: "air",
    domain: "air",
    water: true,
    indirect: false,
    capture: false,
    repair: 0,
    radar: 3,
    blurb: "The other fork after the heavy bomber. Radar 3, and it can cross water. Less bomb than the strategic bomber, much better eyes.",
  },
  {
    id: "heavygun",
    name: "Heavy Howitzer",
    cost: 1180,
    build: 2,
    hp: 14,
    move: 6,
    minRange: 3,
    maxRange: 10,
    vision: 1,
    atk: 16,
    vs: { light: 1.05, armor: 1.4, air: 0, structure: 2.1 },
    armor: "light",
    domain: "ground",
    indirect: true,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "Past the siege mortar. A direct heavy shell, range 3–10. More accurate on tanks than the rocket artillery. Cannot hit aircraft. Radar 1.",
  },
  {
    id: "mlrs",
    name: "Rocket Artillery",
    cost: 1240,
    build: 2,
    hp: 12,
    move: 9,
    minRange: 4,
    maxRange: 12,
    vision: 1,
    atk: 14,
    vs: { light: 1.25, armor: 1.05, air: 0, structure: 1.7 },
    armor: "light",
    domain: "ground",
    indirect: true,
    capture: false,
    repair: 0,
    radar: 1,
    shots: 2,
    blurb: "The other fork after the siege mortar. Two rocket salvos, range 4–12. Better on troops, worse on a single bunker. Radar 1.",
  },
  {
    id: "dmr",
    name: "Designated Marksman",
    cost: 340,
    build: 1,
    hp: 8,
    move: 13,
    minRange: 2,
    maxRange: 9,
    vision: 3,
    atk: 8,
    vs: { light: 1.8, armor: 0.25, air: 0.05, structure: 0.25 },
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: true,
    repair: 0,
    radar: 1,
    blurb: "The first step past the sniper. Range 2–9, a harder shot, and more health. Still one shot. Ready in one turn. Can capture. Radar 1.",
  },
  {
    id: "sharp",
    name: "Sharpshooter",
    cost: 520,
    build: 1,
    hp: 9,
    move: 13,
    minRange: 2,
    maxRange: 10,
    vision: 4,
    atk: 10,
    vs: { light: 1.9, armor: 0.25, air: 0.05, structure: 0.25 },
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: true,
    repair: 0,
    radar: 1,
    blurb: "Farther and harder than the designated marksman. Range 2–10, vision 4. One shot. Ready in one turn. Can capture. Radar 1.",
  },
  {
    id: "longshot",
    name: "Long Rifle",
    cost: 760,
    build: 1,
    hp: 10,
    move: 12,
    minRange: 3,
    maxRange: 12,
    vision: 4,
    atk: 12,
    vs: { light: 2, armor: 0.3, air: 0.05, structure: 0.3 },
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: true,
    repair: 0,
    radar: 1,
    blurb: "The long glass. Range 3–12 and a heavier bullet than the sharpshooter. Useless inside minimum range. Ready in one turn. Can capture. Radar 1.",
  },
  {
    id: "phantom",
    name: "Phantom",
    cost: 1100,
    build: 2,
    hp: 12,
    move: 14,
    minRange: 3,
    maxRange: 13,
    vision: 5,
    atk: 14,
    vs: { light: 2.15, armor: 0.35, air: 0.05, structure: 0.3 },
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: true,
    repair: 0,
    radar: 2,
    blurb: "Range 3–13, vision 5, radar 2. A harder troop shot than the long rifle. Two turns to build. Can capture.",
  },
  {
    id: "counter",
    name: "Counter-Sniper",
    cost: 460,
    build: 1,
    hp: 8,
    move: 14,
    minRange: 1,
    maxRange: 7,
    vision: 3,
    atk: 7,
    vs: { light: 1.65, armor: 0.3, air: 0.05, structure: 0.25 },
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: true,
    repair: 0,
    radar: 1,
    shots: 2,
    blurb: "The other fork after the designated marksman. Two shots, range 7, and faster. Built to hunt rifle teams. Ready in one turn. Can capture. Radar 1.",
  },
  {
    id: "overwatch",
    name: "Overwatch",
    cost: 680,
    build: 1,
    hp: 10,
    move: 14,
    minRange: 1,
    maxRange: 8,
    vision: 4,
    atk: 8,
    vs: { light: 1.75, armor: 0.35, air: 0.08, structure: 0.3 },
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: true,
    repair: 0,
    radar: 1,
    shots: 2,
    blurb: "Two shots, range 8, tougher than the counter-sniper. Holds a lane. Ready in one turn. Can capture. Radar 1.",
  },
  {
    id: "stalker",
    name: "Stalker",
    cost: 960,
    build: 1,
    hp: 12,
    move: 16,
    minRange: 1,
    maxRange: 9,
    vision: 4,
    atk: 9,
    vs: { light: 1.85, armor: 0.4, air: 0.08, structure: 0.35 },
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: true,
    repair: 0,
    radar: 2,
    shots: 2,
    blurb: "Faster than overwatch, range 9, two shots, radar 2. Still ready in one turn. Can capture.",
  },
  {
    id: "materiel",
    name: "Anti-Materiel",
    cost: 480,
    build: 1,
    hp: 9,
    move: 8,
    minRange: 2,
    maxRange: 8,
    vision: 2,
    atk: 11,
    vs: { light: 1.25, armor: 0.7, air: 0, structure: 0.65 },
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "The other fork off the sniper. A heavy rifle that punches light armor and buildings. Slower. Cannot capture. Ready in one turn. Radar 1.",
  },
  {
    id: "fifty",
    name: "Fifty Cal",
    cost: 820,
    build: 2,
    hp: 11,
    move: 8,
    minRange: 2,
    maxRange: 10,
    vision: 2,
    atk: 14,
    vs: { light: 1.2, armor: 0.95, air: 0.1, structure: 0.85 },
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "Harder and farther than the anti-materiel rifle. Range 2–10. It can crack a light vehicle. Two turns. Cannot capture. Radar 1.",
  },
  {
    id: "sabot",
    name: "Sabot Rifle",
    cost: 1180,
    build: 2,
    hp: 13,
    move: 8,
    minRange: 2,
    maxRange: 11,
    vision: 2,
    atk: 16,
    vs: { light: 1.15, armor: 1.15, air: 0.1, structure: 0.95 },
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "Range 2–11 and it hurts tanks more than the fifty cal. Two turns. Cannot capture. Radar 1.",
  },
  {
    id: "seeder",
    name: "Seed Truck",
    cost: 420,
    build: 1,
    hp: 12,
    move: 11,
    minRange: 0,
    maxRange: 0,
    vision: 2,
    atk: 0,
    vs: NONE,
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    mines: 6,
    blurb: "The mine-count fork. Carries 6, one more move than the minelayer, and ready in one turn. Restock is still 70 a mine. Unarmed. Radar 1.",
  },
  {
    id: "planter",
    name: "Field Planter",
    cost: 640,
    build: 1,
    hp: 14,
    move: 12,
    minRange: 0,
    maxRange: 0,
    vision: 2,
    atk: 0,
    vs: NONE,
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    mines: 8,
    blurb: "Eight mines and a little faster than the seed truck. Ready in one turn. Unarmed. Radar 1.",
  },
  {
    id: "carpet",
    name: "Carpet Layer",
    cost: 980,
    build: 2,
    hp: 16,
    move: 12,
    minRange: 0,
    maxRange: 0,
    vision: 3,
    atk: 0,
    vs: NONE,
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 2,
    mines: 12,
    blurb: "Twelve mines, vision 3, radar 2. Two turns to build. Unarmed.",
  },
  {
    id: "prowler",
    name: "Raider Layer",
    cost: 400,
    build: 1,
    hp: 10,
    move: 16,
    minRange: 0,
    maxRange: 0,
    vision: 3,
    atk: 0,
    vs: NONE,
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    mines: 4,
    blurb: "The speed fork. Same 4 mines as the minelayer, but move 16 and vision 3. Ready in one turn. Unarmed. Radar 1.",
  },
  {
    id: "nightlay",
    name: "Night Layer",
    cost: 640,
    build: 1,
    hp: 12,
    move: 18,
    minRange: 0,
    maxRange: 0,
    vision: 3,
    atk: 0,
    vs: NONE,
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 2,
    mines: 6,
    blurb: "Six mines, move 18, radar 2. Faster and fuller than the raider layer. Ready in one turn. Unarmed.",
  },
  {
    id: "slip",
    name: "Slip Layer",
    cost: 900,
    build: 1,
    hp: 14,
    move: 22,
    minRange: 0,
    maxRange: 0,
    vision: 4,
    atk: 0,
    vs: NONE,
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 2,
    mines: 8,
    blurb: "Eight mines, move 22, vision 4, radar 2. Still ready in one turn. Unarmed.",
  },
  {
    id: "hull",
    name: "Hull Layer",
    cost: 620,
    build: 2,
    hp: 22,
    move: 9,
    minRange: 1,
    maxRange: 1,
    vision: 2,
    atk: 6,
    vs: { light: 0.8, armor: 0.5, air: 0, structure: 0.6 },
    armor: "armor",
    domain: "ground",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    mines: 5,
    blurb: "The armor fork. Five mines behind plate, and a short gun if something stands on it. Two turns. Radar 1.",
  },
  {
    id: "breachlay",
    name: "Breach Layer",
    cost: 900,
    build: 2,
    hp: 28,
    move: 9,
    minRange: 1,
    maxRange: 1,
    vision: 2,
    atk: 8,
    vs: { light: 0.9, armor: 0.6, air: 0, structure: 0.8 },
    armor: "armor",
    domain: "ground",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    mines: 7,
    blurb: "Seven mines and more plate than the hull layer. The gun is still only range 1. Two turns. Radar 1.",
  },
  {
    id: "siegelay",
    name: "Siege Layer",
    cost: 1280,
    build: 2,
    hp: 36,
    move: 9,
    minRange: 1,
    maxRange: 2,
    vision: 2,
    atk: 10,
    vs: { light: 1, armor: 0.7, air: 0, structure: 1 },
    armor: "armor",
    domain: "ground",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    mines: 9,
    blurb: "Past the siege layer. Nine mines, heavy plate, and a range-2 gun. Two turns. Radar 1.",
  },
  {
    id: "apex",
    name: "Apex Rifle",
    cost: 1480,
    build: 2,
    hp: 14,
    move: 14,
    minRange: 3,
    maxRange: 14,
    vision: 6,
    atk: 15,
    vs: { light: 2.2, armor: 0.4, air: 0.05, structure: 0.35 },
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: true,
    repair: 0,
    radar: 2,
    blurb: "Past the phantom. Range 3–14 and vision 6. One step farther, not a new weapon. Same two-turn build. Can capture. Radar 2.",
  },
  {
    id: "shade",
    name: "Shade",
    cost: 1280,
    build: 1,
    hp: 13,
    move: 17,
    minRange: 1,
    maxRange: 10,
    vision: 5,
    atk: 11,
    vs: { light: 1.95, armor: 0.45, air: 0.1, structure: 0.4 },
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: true,
    repair: 0,
    radar: 2,
    shots: 2,
    blurb: "Past the stalker. Two shots, range 10, move 17, a harder hit. Still ready in one turn. Can capture. Radar 2.",
  },
  {
    id: "penetrator",
    name: "Penetrator",
    cost: 1560,
    build: 2,
    hp: 14,
    move: 8,
    minRange: 2,
    maxRange: 12,
    vision: 2,
    atk: 18,
    vs: { light: 1.1, armor: 1.4, air: 0.12, structure: 1.1 },
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "Past the sabot rifle. Range 2–12 and it punches tanks harder. Same two-turn build. Cannot capture. Radar 1.",
  },
  {
    id: "superheavy",
    name: "Superheavy",
    cost: 1560,
    build: 2,
    hp: 16,
    move: 5,
    minRange: 3,
    maxRange: 11,
    vision: 1,
    atk: 18,
    vs: { light: 1.1, armor: 1.5, air: 0, structure: 2.25 },
    armor: "light",
    domain: "ground",
    indirect: true,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "Past the heavy howitzer. Range 3–11 and a slightly heavier shell. Same two-turn build. Cannot hit aircraft. Radar 1.",
  },
  {
    id: "barrage",
    name: "Barrage",
    cost: 1620,
    build: 2,
    hp: 13,
    move: 9,
    minRange: 4,
    maxRange: 13,
    vision: 1,
    atk: 16,
    vs: { light: 1.35, armor: 1.1, air: 0, structure: 1.85 },
    armor: "light",
    domain: "ground",
    indirect: true,
    capture: false,
    repair: 0,
    radar: 1,
    shots: 2,
    blurb: "Past the rocket artillery. Two salvos, range 4–13, a harder rocket. Same two-turn build. Cannot hit aircraft. Radar 1.",
  },
  {
    id: "skylance",
    name: "Sky Lance",
    cost: 1100,
    build: 1,
    hp: 14,
    move: 10,
    minRange: 2,
    maxRange: 10,
    vision: 2,
    atk: 14,
    vs: { light: 0.22, armor: 0.1, air: 2.35, structure: 0.06 },
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 4,
    blurb: "Past the SAM. Range 2–10 and radar 4. Still ready in one turn. Weak against ground.",
  },
  {
    id: "marshal",
    name: "Marshal",
    cost: 2480,
    build: 2,
    hp: 46,
    move: 9,
    minRange: 1,
    maxRange: 6,
    vision: 3,
    atk: 17,
    vs: { light: 1.2, armor: 1.8, air: 0, structure: 1.5 },
    armor: "armor",
    domain: "ground",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 4,
    blurb: "Past the command tank. Radar 4, vision 3, and a longer gun. Same two-turn build. Cannot hit aircraft.",
  },
  {
    id: "glaive",
    name: "Glaive",
    cost: 2680,
    build: 2,
    hp: 60,
    move: 9,
    minRange: 1,
    maxRange: 7,
    vision: 1,
    atk: 21,
    vs: { light: 1.3, armor: 2.2, air: 0, structure: 1.95 },
    armor: "armor",
    domain: "ground",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "Past the spearhead tank. One shot, range 7, a little more health and a harder gun. Same two-turn build. Cannot hit aircraft. Radar 1.",
  },
  {
    id: "flagship",
    name: "Flagship",
    cost: 2480,
    build: 2,
    hp: 46,
    move: 12,
    minRange: 3,
    maxRange: 11,
    vision: 2,
    atk: 17,
    vs: { light: 1, armor: 1.75, air: 0.45, structure: 1.85 },
    armor: "armor",
    domain: "sea",
    indirect: true,
    capture: false,
    repair: 0,
    radar: 2,
    shots: 2,
    blurb: "Past the battlecruiser. Range 3–11, radar 2, two shots. Same two-turn build.",
  },
  {
    id: "citadel",
    name: "Citadel",
    cost: 2360,
    build: 2,
    hp: 44,
    move: 6,
    minRange: 2,
    maxRange: 9,
    vision: 1,
    atk: 21,
    vs: { light: 1.1, armor: 1.45, air: 0.1, structure: 2.6 },
    armor: "armor",
    domain: "sea",
    indirect: true,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "Past the monitor. A heavier shore gun, range 2–9. Same two-turn build. Radar 1.",
  },
  {
    id: "boomer",
    name: "Boomer",
    cost: 1980,
    build: 2,
    hp: 20,
    move: 12,
    minRange: 4,
    maxRange: 12,
    vision: 1,
    atk: 16,
    vs: { light: 0.55, armor: 1.4, air: 0, structure: 1.9 },
    armor: "armor",
    domain: "sea",
    indirect: true,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "Past the cruise sub. Missiles at range 4–12. Same two-turn build. Cannot hit aircraft. Radar 1.",
  },
  {
    id: "killer",
    name: "Hunter-Killer",
    cost: 1880,
    build: 2,
    hp: 22,
    move: 18,
    minRange: 1,
    maxRange: 7,
    vision: 2,
    atk: 19,
    vs: { light: 0.28, armor: 2.5, air: 0, structure: 0.5 },
    armor: "armor",
    domain: "sea",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "Past the attack sub. Faster, range 7, and a harder torpedo. Same two-turn build. Cannot hit aircraft. Radar 1.",
  },
  {
    id: "spectre",
    name: "Spectre",
    cost: 1860,
    build: 2,
    hp: 16,
    move: 24,
    minRange: 1,
    maxRange: 9,
    vision: 3,
    atk: 14,
    vs: { light: 0.45, armor: 0.3, air: 2.8, structure: 0.2 },
    armor: "air",
    domain: "air",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 3,
    shots: 2,
    blurb: "Past the night fighter. Range 9, radar 3, two shots. Same two-turn build. Still weak on the ground.",
  },
  {
    id: "raptor",
    name: "Raptor",
    cost: 1920,
    build: 1,
    hp: 14,
    move: 30,
    minRange: 1,
    maxRange: 7,
    vision: 1,
    atk: 15,
    vs: { light: 0.35, armor: 0.2, air: 2.8, structure: 0.12 },
    armor: "air",
    domain: "air",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    shots: 2,
    blurb: "Past the dogfighter. Two shots, a little faster, and ready in one turn. Radar 1.",
  },
  {
    id: "arsenal",
    name: "Arsenal",
    cost: 2460,
    build: 2,
    hp: 22,
    move: 14,
    minRange: 2,
    maxRange: 6,
    vision: 1,
    atk: 19,
    vs: { light: 1.35, armor: 1.6, air: 0, structure: 2.6 },
    armor: "air",
    domain: "air",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "Past the strategic bomber. A harder bomb and range 6. Same two-turn build. Cannot dogfight. Radar 1.",
  },
  {
    id: "seamark",
    name: "Seamark",
    cost: 1980,
    build: 1,
    hp: 16,
    move: 20,
    minRange: 1,
    maxRange: 4,
    vision: 3,
    atk: 14,
    vs: { light: 1.2, armor: 1.25, air: 0, structure: 2 },
    armor: "air",
    domain: "air",
    water: true,
    indirect: false,
    capture: false,
    repair: 0,
    radar: 4,
    blurb: "Past the pathfinder. Radar 4, it crosses water, and it is ready in one turn. Less bomb than the arsenal.",
  },
  {
    id: "blanket",
    name: "Blanket",
    cost: 1280,
    build: 2,
    hp: 18,
    move: 12,
    minRange: 0,
    maxRange: 0,
    vision: 3,
    atk: 0,
    vs: NONE,
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 2,
    mines: 14,
    blurb: "Past the carpet layer. Fourteen mines. Same two-turn build. Unarmed. Radar 2.",
  },
  {
    id: "ghost",
    name: "Ghost Layer",
    cost: 1180,
    build: 1,
    hp: 14,
    move: 23,
    minRange: 0,
    maxRange: 0,
    vision: 5,
    atk: 0,
    vs: NONE,
    armor: "light",
    domain: "ground",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 2,
    mines: 9,
    blurb: "Past the slip layer. Nine mines, move 23, vision 5. Still ready in one turn. Unarmed. Radar 2.",
  },
  {
    id: "fortress",
    name: "Fortress Layer",
    cost: 1680,
    build: 2,
    hp: 40,
    move: 8,
    minRange: 1,
    maxRange: 3,
    vision: 2,
    atk: 11,
    vs: { light: 1.05, armor: 0.8, air: 0, structure: 1.15 },
    armor: "armor",
    domain: "ground",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    mines: 10,
    blurb: "Past the siege layer. Ten mines, a little more plate, and a range-3 gun. Same two-turn build. Radar 1.",
  },
  {
    id: "carrier",
    name: "Carrier",
    cost: 2800,
    build: 2,
    hp: 50,
    move: 10,
    minRange: 1,
    maxRange: 6,
    vision: 3,
    atk: 12,
    vs: { light: 0.7, armor: 0.7, air: 1.15, structure: 0.55 },
    armor: "armor",
    domain: "sea",
    indirect: false,
    capture: false,
    repair: 3,
    radar: 5,
    shots: 2,
    blurb: "Past the flagship. Shorter guns, range 6, two shots. Radar 5, and it heals 3 on a friendly within 2 squares. Same two-turn build.",
  },
  {
    id: "aegis",
    name: "Aegis",
    cost: 1680,
    build: 2,
    hp: 24,
    move: 15,
    minRange: 1,
    maxRange: 8,
    vision: 2,
    atk: 11,
    vs: { light: 0.5, armor: 0.85, air: 1.85, structure: 0.35 },
    armor: "armor",
    domain: "sea",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 3,
    shots: 2,
    blurb: "Past the escort. Range 8, two shots, radar 3. A step better against aircraft. Same two-turn build.",
  },
  {
    id: "rampart",
    name: "Rampart",
    cost: 2580,
    build: 2,
    hp: 48,
    move: 6,
    minRange: 2,
    maxRange: 10,
    vision: 1,
    atk: 22,
    vs: { light: 1.1, armor: 1.5, air: 0.1, structure: 2.7 },
    armor: "armor",
    domain: "sea",
    indirect: true,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "Past the citadel. Range 2–10 and a slightly harder shore gun. Same two-turn build. Radar 1.",
  },
  {
    id: "marlin",
    name: "Marlin",
    cost: 2060,
    build: 2,
    hp: 24,
    move: 18,
    minRange: 1,
    maxRange: 8,
    vision: 2,
    atk: 20,
    vs: { light: 0.28, armor: 2.55, air: 0, structure: 0.5 },
    armor: "armor",
    domain: "sea",
    indirect: false,
    capture: false,
    repair: 0,
    radar: 1,
    blurb: "Past the hunter-killer. Range 8 and a harder torpedo. Same speed and two-turn build. Cannot hit aircraft. Radar 1.",
  },
];

export const STRUCTS: StructDef[] = [
  {
    id: "spire",
    name: "Headquarters",
    cost: 0,
    hp: 22,
    minRange: 0,
    maxRange: 0,
    vision: 2,
    radar: 0,
    atk: 0,
    vs: NONE,
    dr: 0.12,
    income: 500,
    blocks: false,
    property: true,
    blurb: "Your headquarters. Shoot it down to win. It pays 500 and is where you build. Its health is the Base HP you set for the match.",
  },
  {
    id: "outpost",
    name: "Supply Base",
    cost: 600,
    build: 2,
    hp: 18,
    minRange: 0,
    maxRange: 0,
    vision: 2,
    radar: 0,
    atk: 0,
    vs: NONE,
    dr: 0.08,
    income: 200,
    blocks: false,
    property: true,
    blurb: "Capturable income and a second place to deploy. +200 a turn.",
  },
  {
    id: "radar",
    name: "Radar",
    cost: 360,
    build: 2,
    hp: 10,
    minRange: 0,
    maxRange: 0,
    vision: 2,
    radar: 5,
    atk: 0,
    vs: NONE,
    dr: 0.05,
    income: 0,
    blocks: true,
    property: false,
    blurb: "Sees a wide radius and shows enemy contacts as blips. Ridges still block the view.",
  },
  {
    id: "turret",
    name: "Machine Gun",
    cost: 420,
    build: 2,
    hp: 12,
    minRange: 1,
    maxRange: 3,
    vision: 1,
    radar: 1,
    atk: 5,
    vs: { light: 1.4, armor: 0.35, air: 0, structure: 0.3 },
    dr: 0.1,
    income: 0,
    blocks: true,
    property: false,
    shots: 3,
    blurb: "Fixed gun, range 4, radar 1. Fires three times, including during the enemy turn. Ignores aircraft.",
  },
  {
    id: "bunker",
    name: "Bunker",
    cost: 380,
    build: 2,
    hp: 24,
    minRange: 1,
    maxRange: 3,
    vision: 1,
    radar: 1,
    atk: 4,
    vs: { light: 1.1, armor: 0.4, air: 0.1, structure: 0.25 },
    dr: 0.35,
    income: 0,
    blocks: true,
    property: false,
    shots: 2,
    blurb: "Concrete bunker. Two shots, range 4, radar 1. Fires during the enemy turn if something is in range.",
  },
  {
    id: "barrier",
    name: "Wall",
    cost: 110,
    build: 1,
    hp: 12,
    minRange: 0,
    maxRange: 0,
    vision: 1,
    radar: 0,
    atk: 0,
    vs: NONE,
    dr: 0.1,
    income: 0,
    blocks: true,
    property: false,
    blurb: "Wall. Blocks ground movement until someone knocks it down.",
  },
  {
    id: "mine",
    name: "Mine",
    cost: 140,
    build: 1,
    hp: 1,
    minRange: 0,
    maxRange: 0,
    vision: 0,
    radar: 0,
    atk: 0,
    vs: NONE,
    dr: 0,
    income: 0,
    blocks: false,
    property: false,
    blurb: "Buried. The enemy cannot see it. A ground unit that enters takes 8 and stops.",
  },
  {
    id: "aa",
    name: "AA Gun",
    cost: 460,
    build: 2,
    hp: 12,
    minRange: 1,
    maxRange: 6,
    vision: 1,
    radar: 1,
    atk: 8,
    vs: { light: 0.25, armor: 0.1, air: 1.8, structure: 0.1 },
    dr: 0.08,
    income: 0,
    blocks: true,
    property: false,
    shots: 2,
    blurb: "Fixed anti-air, range 6, radar 1. Two shots. Fires at aircraft during the enemy turn too.",
  },
  {
    id: "pit",
    name: "Gun Pit",
    cost: 860,
    build: 2,
    hp: 20,
    minRange: 2,
    maxRange: 7,
    vision: 1,
    radar: 1,
    atk: 12,
    vs: { light: 0.85, armor: 1.25, air: 0, structure: 1.75 },
    dr: 0.16,
    income: 0,
    blocks: true,
    property: false,
    blurb: "Fixed siege gun, range 2–7, radar 1. Hits buildings harder than a machine gun. Fires during the enemy turn. Cannot hit aircraft.",
  },
  {
    id: "flak",
    name: "Flak Tower",
    cost: 1040,
    build: 2,
    hp: 18,
    minRange: 1,
    maxRange: 8,
    vision: 2,
    radar: 2,
    atk: 11,
    vs: { light: 0.3, armor: 0.15, air: 2.15, structure: 0.1 },
    dr: 0.1,
    income: 0,
    blocks: true,
    property: false,
    shots: 2,
    blurb: "The tall anti-air. Range 8, two shots, radar 2. The Screen comes after it.",
  },
  {
    id: "tower",
    name: "Watchtower",
    cost: 280,
    build: 1,
    hp: 10,
    minRange: 0,
    maxRange: 0,
    vision: 4,
    radar: 3,
    atk: 0,
    vs: NONE,
    dr: 0.05,
    income: 0,
    blocks: false,
    property: false,
    blurb: "Cheap eyes. Vision 4 and radar 3. Unarmed. Ready in one turn. Does not block movement.",
  },
  {
    id: "nest",
    name: "Hardpoint",
    cost: 720,
    build: 2,
    hp: 32,
    minRange: 1,
    maxRange: 4,
    vision: 1,
    radar: 1,
    atk: 6,
    vs: { light: 1.35, armor: 0.55, air: 0.15, structure: 0.4 },
    dr: 0.4,
    income: 0,
    blocks: true,
    property: false,
    shots: 2,
    blurb: "Past the bunker. More health, range 4, two shots. Fires during the enemy turn. Radar 1.",
  },
  {
    id: "net",
    name: "Air Screen",
    cost: 1280,
    build: 2,
    hp: 22,
    minRange: 1,
    maxRange: 9,
    vision: 2,
    radar: 3,
    atk: 13,
    vs: { light: 0.25, armor: 0.12, air: 2.4, structure: 0.1 },
    dr: 0.12,
    income: 0,
    blocks: true,
    property: false,
    shots: 2,
    blurb: "Past the flak tower. Range 9, two shots, radar 3. The farthest anti-air you can plant.",
  },
  {
    id: "pillbox",
    name: "Pillbox",
    cost: 860,
    build: 2,
    hp: 44,
    minRange: 1,
    maxRange: 3,
    vision: 1,
    radar: 1,
    atk: 8,
    vs: { light: 1.5, armor: 0.7, air: 0.1, structure: 0.45 },
    dr: 0.5,
    income: 0,
    blocks: true,
    property: false,
    shots: 3,
    blurb: "Past the hardpoint. Three shots, short range, and it is very hard to break. Fires during the enemy turn. Radar 1.",
  },
  {
    id: "casemate",
    name: "Casemate",
    cost: 980,
    build: 2,
    hp: 30,
    minRange: 2,
    maxRange: 6,
    vision: 1,
    radar: 1,
    atk: 11,
    vs: { light: 0.9, armor: 1.15, air: 0, structure: 1.35 },
    dr: 0.35,
    income: 0,
    blocks: true,
    property: false,
    blurb: "The other fork after the hardpoint. A concrete gun, range 2–6, aimed at tanks and buildings. Fires during the enemy turn. Radar 1.",
  },
  {
    id: "samsite",
    name: "SAM Site",
    cost: 1560,
    build: 2,
    hp: 20,
    minRange: 2,
    maxRange: 11,
    vision: 2,
    radar: 4,
    atk: 15,
    vs: { light: 0.2, armor: 0.1, air: 2.7, structure: 0.08 },
    dr: 0.1,
    income: 0,
    blocks: true,
    property: false,
    blurb: "Past the air screen. One long missile, range 2–11, radar 4. The farthest shot you can plant. Weak up close.",
  },
  {
    id: "point",
    name: "Point Defense",
    cost: 1320,
    build: 1,
    hp: 18,
    minRange: 1,
    maxRange: 5,
    vision: 2,
    radar: 2,
    atk: 8,
    vs: { light: 0.35, armor: 0.15, air: 2.2, structure: 0.1 },
    dr: 0.1,
    income: 0,
    blocks: true,
    property: false,
    shots: 4,
    blurb: "The other fork after the air screen. Four close shots. Ready in one turn. It shreds aircraft that fly over it. Radar 2.",
  },
  {
    id: "redoubt",
    name: "Redoubt",
    cost: 1100,
    build: 2,
    hp: 52,
    minRange: 1,
    maxRange: 3,
    vision: 1,
    radar: 1,
    atk: 9,
    vs: { light: 1.6, armor: 0.8, air: 0.1, structure: 0.5 },
    dr: 0.55,
    income: 0,
    blocks: true,
    property: false,
    shots: 3,
    blurb: "Past the pillbox. More health, three shots, still short range. Fires during the enemy turn. Radar 1.",
  },
  {
    id: "coastgun",
    name: "Coast Gun",
    cost: 1240,
    build: 2,
    hp: 34,
    minRange: 2,
    maxRange: 8,
    vision: 1,
    radar: 1,
    atk: 13,
    vs: { light: 0.95, armor: 1.3, air: 0, structure: 1.55 },
    dr: 0.35,
    income: 0,
    blocks: true,
    property: false,
    blurb: "Past the casemate. Range 2–8, aimed at tanks, ships, and buildings. Fires during the enemy turn. Radar 1.",
  },
  {
    id: "umbrella",
    name: "Umbrella",
    cost: 1880,
    build: 2,
    hp: 22,
    minRange: 2,
    maxRange: 12,
    vision: 2,
    radar: 5,
    atk: 16,
    vs: { light: 0.2, armor: 0.1, air: 2.8, structure: 0.08 },
    dr: 0.1,
    income: 0,
    blocks: true,
    property: false,
    blurb: "Past the SAM site. Range 2–12 and radar 5. One step past the longest plant, not a new ceiling. Weak up close.",
  },
  {
    id: "ciws",
    name: "Close-In Gun",
    cost: 1540,
    build: 1,
    hp: 20,
    minRange: 1,
    maxRange: 6,
    vision: 2,
    radar: 2,
    atk: 9,
    vs: { light: 0.4, armor: 0.18, air: 2.4, structure: 0.12 },
    dr: 0.12,
    income: 0,
    blocks: true,
    property: false,
    shots: 4,
    blurb: "Past point defense. Four shots, range 6. Ready in one turn. Radar 2.",
  },
  {
    id: "bastion",
    name: "Bastion",
    cost: 1280,
    build: 2,
    hp: 58,
    minRange: 1,
    maxRange: 3,
    vision: 1,
    radar: 1,
    atk: 10,
    vs: { light: 1.65, armor: 0.85, air: 0.1, structure: 0.55 },
    dr: 0.58,
    income: 0,
    blocks: true,
    property: false,
    shots: 3,
    blurb: "Past the redoubt. A little more health and a slightly harder gun. Still range 3, three shots. Fires during the enemy turn. Radar 1.",
  },
  {
    id: "harbor",
    name: "Harbor Gun",
    cost: 1420,
    build: 2,
    hp: 36,
    minRange: 2,
    maxRange: 9,
    vision: 1,
    radar: 1,
    atk: 14,
    vs: { light: 0.95, armor: 1.35, air: 0, structure: 1.65 },
    dr: 0.35,
    income: 0,
    blocks: true,
    property: false,
    blurb: "Past the coast gun. Range 2–9. A step harder on ships and buildings. Fires during the enemy turn. Cannot hit aircraft. Radar 1.",
  },
  {
    id: "skyfort",
    name: "Skyfort",
    cost: 2060,
    build: 2,
    hp: 24,
    minRange: 2,
    maxRange: 12,
    vision: 2,
    radar: 6,
    atk: 17,
    vs: { light: 0.2, armor: 0.1, air: 2.9, structure: 0.08 },
    dr: 0.1,
    income: 0,
    blocks: true,
    property: false,
    blurb: "Past the umbrella. Same range 2–12, radar 6, and a slightly harder missile. Fires during the enemy turn.",
  },
  {
    id: "phalanx",
    name: "Phalanx",
    cost: 1720,
    build: 1,
    hp: 22,
    minRange: 1,
    maxRange: 6,
    vision: 2,
    radar: 2,
    atk: 10,
    vs: { light: 0.4, armor: 0.18, air: 2.55, structure: 0.12 },
    dr: 0.12,
    income: 0,
    blocks: true,
    property: false,
    shots: 4,
    blurb: "Past the close-in gun. Still four shots at range 6, a little harder on aircraft. Ready in one turn. Radar 2.",
  },
  {
    id: "mast",
    name: "Signal Mast",
    cost: 360,
    build: 1,
    hp: 12,
    minRange: 0,
    maxRange: 0,
    vision: 5,
    radar: 4,
    atk: 0,
    vs: NONE,
    dr: 0.05,
    income: 0,
    blocks: false,
    property: false,
    blurb: "Past the watchtower. Vision 5 and radar 4. Unarmed. Ready in one turn. Does not block movement.",
  },
];

export const UNIT_BY: Record<UnitKind, UnitDef> = Object.fromEntries(UNITS.map((u) => [u.id, u])) as Record<
  UnitKind,
  UnitDef
>;

export const STRUCT_BY: Record<StructKind, StructDef> = Object.fromEntries(STRUCTS.map((s) => [s.id, s])) as Record<
  StructKind,
  StructDef
>;

export const BUY_ORDER: BuyId[] = [
  "squad", "marksman", "bullhead", "tank", "pike", "lobber", "aagun", "rotor", "destroyer", "radar", "barrier", "mine", "outpost",
  "spotter", "grenade", "scorch", "breacher", "demo", "mg", "ranger", "sapper", "pioneer", "engineer", "field", "salvo", "siege", "heavygun", "superheavy", "mlrs", "barrage", "sam", "skylance",
  "dmr", "sharp", "longshot", "phantom", "apex", "counter", "overwatch", "stalker", "shade", "materiel", "fifty", "sabot", "penetrator",
  "seeder", "planter", "carpet", "blanket", "prowler", "nightlay", "slip", "ghost", "hull", "breachlay", "siegelay", "fortress",
  "scout", "hunter", "atgm", "ambush", "ram", "breaker", "wrecker", "dozer", "spg", "heavy", "guard", "monarch", "command", "marshal", "spear", "glaive",
  "raider", "ship", "battery", "dread", "monitor", "citadel", "rampart", "battle", "flagship", "carrier", "frigate", "lancer", "asw", "escort", "aegis", "sub", "lurker", "cruise", "boomer", "wolf", "killer", "marlin",
  "tender", "thunder", "drone", "eye", "armed", "radarplane", "fighter", "lance", "ace", "night", "spectre", "dogfight", "raptor", "bomber", "strike", "vault", "strategic", "arsenal", "pathfinder", "seamark",
  "dish", "layer", "tower", "mast", "turret", "bunker", "nest", "pillbox", "redoubt", "bastion", "casemate", "coastgun", "harbor", "aa", "flak", "net", "samsite", "umbrella", "skyfort", "point", "ciws", "phalanx", "pit",
];

export function isUnitKind(id: string): id is UnitKind {
  return id in UNIT_BY;
}

/** Always buyable, even when the account has discovered nothing. */
export const BASIC_KIT: BuyId[] = [
  "squad", "marksman", "bullhead", "tank", "pike", "lobber", "aagun", "rotor", "destroyer", "radar", "barrier", "mine", "outpost",
];

export const FREE_BUY: BuyId[] = BASIC_KIT;

export interface ResearchNode {
  id: BuyId;
  line: "Rifles" | "Snipers" | "Minelayers" | "Armor" | "Fleet" | "Air" | "Works";
  after: BuyId | null;
  rp: number;
}

export const RESEARCH: ResearchNode[] = [
  { id: "spotter", line: "Rifles", after: "marksman", rp: 80 },
  { id: "grenade", line: "Rifles", after: "marksman", rp: 120 },
  { id: "scorch", line: "Rifles", after: "grenade", rp: 220 },
  { id: "breacher", line: "Rifles", after: "scorch", rp: 320 },
  { id: "demo", line: "Rifles", after: "scorch", rp: 340 },
  { id: "mg", line: "Rifles", after: "marksman", rp: 180 },
  { id: "ranger", line: "Rifles", after: "mg", rp: 280 },
  { id: "sapper", line: "Rifles", after: "ranger", rp: 360 },
  { id: "pioneer", line: "Rifles", after: "sapper", rp: 440 },
  { id: "engineer", line: "Rifles", after: "sapper", rp: 460 },
  { id: "field", line: "Rifles", after: "lobber", rp: 200 },
  { id: "salvo", line: "Rifles", after: "field", rp: 320 },
  { id: "siege", line: "Rifles", after: "salvo", rp: 460 },
  { id: "heavygun", line: "Rifles", after: "siege", rp: 580 },
  { id: "superheavy", line: "Rifles", after: "heavygun", rp: 760 },
  { id: "mlrs", line: "Rifles", after: "siege", rp: 620 },
  { id: "barrage", line: "Rifles", after: "mlrs", rp: 800 },
  { id: "sam", line: "Rifles", after: "aagun", rp: 300 },
  { id: "skylance", line: "Rifles", after: "sam", rp: 480 },
  { id: "dmr", line: "Snipers", after: "marksman", rp: 140 },
  { id: "sharp", line: "Snipers", after: "dmr", rp: 280 },
  { id: "longshot", line: "Snipers", after: "sharp", rp: 460 },
  { id: "phantom", line: "Snipers", after: "longshot", rp: 680 },
  { id: "apex", line: "Snipers", after: "phantom", rp: 860 },
  { id: "counter", line: "Snipers", after: "dmr", rp: 240 },
  { id: "overwatch", line: "Snipers", after: "counter", rp: 400 },
  { id: "stalker", line: "Snipers", after: "overwatch", rp: 560 },
  { id: "shade", line: "Snipers", after: "stalker", rp: 740 },
  { id: "materiel", line: "Snipers", after: "marksman", rp: 200 },
  { id: "fifty", line: "Snipers", after: "materiel", rp: 380 },
  { id: "sabot", line: "Snipers", after: "fifty", rp: 560 },
  { id: "penetrator", line: "Snipers", after: "sabot", rp: 760 },
  { id: "layer", line: "Minelayers", after: "dish", rp: 180 },
  { id: "seeder", line: "Minelayers", after: "layer", rp: 160 },
  { id: "planter", line: "Minelayers", after: "seeder", rp: 320 },
  { id: "carpet", line: "Minelayers", after: "planter", rp: 500 },
  { id: "blanket", line: "Minelayers", after: "carpet", rp: 680 },
  { id: "prowler", line: "Minelayers", after: "layer", rp: 180 },
  { id: "nightlay", line: "Minelayers", after: "prowler", rp: 340 },
  { id: "slip", line: "Minelayers", after: "nightlay", rp: 520 },
  { id: "ghost", line: "Minelayers", after: "slip", rp: 700 },
  { id: "hull", line: "Minelayers", after: "layer", rp: 240 },
  { id: "breachlay", line: "Minelayers", after: "hull", rp: 420 },
  { id: "siegelay", line: "Minelayers", after: "breachlay", rp: 640 },
  { id: "fortress", line: "Minelayers", after: "siegelay", rp: 820 },
  { id: "scout", line: "Armor", after: "bullhead", rp: 140 },
  { id: "hunter", line: "Armor", after: "scout", rp: 320 },
  { id: "atgm", line: "Armor", after: "hunter", rp: 440 },
  { id: "ambush", line: "Armor", after: "hunter", rp: 480 },
  { id: "ram", line: "Armor", after: "tank", rp: 280 },
  { id: "breaker", line: "Armor", after: "ram", rp: 420 },
  { id: "wrecker", line: "Armor", after: "breaker", rp: 640 },
  { id: "dozer", line: "Armor", after: "wrecker", rp: 780 },
  { id: "spg", line: "Armor", after: "wrecker", rp: 820 },
  { id: "heavy", line: "Armor", after: "tank", rp: 360 },
  { id: "guard", line: "Armor", after: "heavy", rp: 520 },
  { id: "monarch", line: "Armor", after: "guard", rp: 700 },
  { id: "command", line: "Armor", after: "monarch", rp: 840 },
  { id: "marshal", line: "Armor", after: "command", rp: 1040 },
  { id: "spear", line: "Armor", after: "monarch", rp: 920 },
  { id: "glaive", line: "Armor", after: "spear", rp: 1100 },
  { id: "raider", line: "Fleet", after: "pike", rp: 160 },
  { id: "ship", line: "Fleet", after: "pike", rp: 320 },
  { id: "battery", line: "Fleet", after: "ship", rp: 520 },
  { id: "dread", line: "Fleet", after: "battery", rp: 680 },
  { id: "monitor", line: "Fleet", after: "dread", rp: 820 },
  { id: "citadel", line: "Fleet", after: "monitor", rp: 1000 },
  { id: "rampart", line: "Fleet", after: "citadel", rp: 1180 },
  { id: "battle", line: "Fleet", after: "dread", rp: 860 },
  { id: "flagship", line: "Fleet", after: "battle", rp: 1040 },
  { id: "carrier", line: "Fleet", after: "flagship", rp: 1200 },
  { id: "frigate", line: "Fleet", after: "destroyer", rp: 360 },
  { id: "lancer", line: "Fleet", after: "frigate", rp: 520 },
  { id: "asw", line: "Fleet", after: "lancer", rp: 640 },
  { id: "escort", line: "Fleet", after: "lancer", rp: 680 },
  { id: "aegis", line: "Fleet", after: "escort", rp: 820 },
  { id: "sub", line: "Fleet", after: "pike", rp: 400 },
  { id: "lurker", line: "Fleet", after: "sub", rp: 560 },
  { id: "cruise", line: "Fleet", after: "lurker", rp: 720 },
  { id: "boomer", line: "Fleet", after: "cruise", rp: 900 },
  { id: "wolf", line: "Fleet", after: "lurker", rp: 760 },
  { id: "killer", line: "Fleet", after: "wolf", rp: 920 },
  { id: "marlin", line: "Fleet", after: "killer", rp: 1080 },
  { id: "tender", line: "Air", after: "rotor", rp: 140 },
  { id: "thunder", line: "Air", after: "rotor", rp: 280 },
  { id: "drone", line: "Air", after: "rotor", rp: 200 },
  { id: "eye", line: "Air", after: "drone", rp: 280 },
  { id: "armed", line: "Air", after: "eye", rp: 380 },
  { id: "radarplane", line: "Air", after: "eye", rp: 400 },
  { id: "fighter", line: "Air", after: "rotor", rp: 300 },
  { id: "lance", line: "Air", after: "fighter", rp: 420 },
  { id: "ace", line: "Air", after: "lance", rp: 560 },
  { id: "night", line: "Air", after: "ace", rp: 700 },
  { id: "spectre", line: "Air", after: "night", rp: 880 },
  { id: "dogfight", line: "Air", after: "ace", rp: 740 },
  { id: "raptor", line: "Air", after: "dogfight", rp: 900 },
  { id: "bomber", line: "Air", after: "fighter", rp: 400 },
  { id: "strike", line: "Air", after: "bomber", rp: 520 },
  { id: "vault", line: "Air", after: "strike", rp: 640 },
  { id: "strategic", line: "Air", after: "vault", rp: 800 },
  { id: "arsenal", line: "Air", after: "strategic", rp: 980 },
  { id: "pathfinder", line: "Air", after: "vault", rp: 760 },
  { id: "seamark", line: "Air", after: "pathfinder", rp: 920 },
  { id: "dish", line: "Works", after: "radar", rp: 140 },
  { id: "tower", line: "Works", after: "radar", rp: 80 },
  { id: "mast", line: "Works", after: "tower", rp: 160 },
  { id: "turret", line: "Works", after: "radar", rp: 160 },
  { id: "bunker", line: "Works", after: "turret", rp: 220 },
  { id: "nest", line: "Works", after: "bunker", rp: 360 },
  { id: "pillbox", line: "Works", after: "nest", rp: 480 },
  { id: "redoubt", line: "Works", after: "pillbox", rp: 640 },
  { id: "bastion", line: "Works", after: "redoubt", rp: 780 },
  { id: "casemate", line: "Works", after: "nest", rp: 520 },
  { id: "coastgun", line: "Works", after: "casemate", rp: 680 },
  { id: "harbor", line: "Works", after: "coastgun", rp: 820 },
  { id: "aa", line: "Works", after: "turret", rp: 240 },
  { id: "flak", line: "Works", after: "aa", rp: 380 },
  { id: "net", line: "Works", after: "flak", rp: 520 },
  { id: "samsite", line: "Works", after: "net", rp: 680 },
  { id: "umbrella", line: "Works", after: "samsite", rp: 860 },
  { id: "skyfort", line: "Works", after: "umbrella", rp: 980 },
  { id: "point", line: "Works", after: "net", rp: 640 },
  { id: "ciws", line: "Works", after: "point", rp: 800 },
  { id: "phalanx", line: "Works", after: "ciws", rp: 940 },
  { id: "pit", line: "Works", after: "turret", rp: 320 },
];

export function lineRoots(line: ResearchNode["line"]): ResearchNode[] {
  const nodes = RESEARCH.filter((node) => node.line === line);
  const ids = new Set(nodes.map((node) => node.id));
  return nodes.filter((node) => !node.after || !ids.has(node.after));
}

export function researchPaths(line: ResearchNode["line"]): BuyId[][] {
  const nodes = RESEARCH.filter((node) => node.line === line);
  const ids = new Set(nodes.map((node) => node.id));
  const kids = new Map<string, ResearchNode[]>();
  for (const node of nodes) {
    if (!node.after || !ids.has(node.after)) continue;
    const list = kids.get(node.after) ?? [];
    list.push(node);
    kids.set(node.after, list);
  }
  const paths: BuyId[][] = [];
  const walk = (node: ResearchNode, path: BuyId[]) => {
    const next = kids.get(node.id) ?? [];
    const here = [...path, node.id];
    if (next.length !== 1) {
      if (!next.length) paths.push(here);
      else for (const child of next) walk(child, here);
      return;
    }
    walk(next[0]!, here);
  };
  for (const root of lineRoots(line)) walk(root, root.after ? [root.after] : []);
  return paths;
}

export function ownedSet(unlocked: string | undefined): Set<string> {
  return new Set((unlocked ?? "").split(",").map((part) => part.trim()).filter(Boolean));
}

export function isDiscovered(unlocked: string | undefined, id: string): boolean {
  if ((FREE_BUY as string[]).includes(id)) return true;
  return ownedSet(unlocked).has(id);
}

export function researchReady(unlocked: string | undefined, id: string): ResearchNode | null {
  const node = RESEARCH.find((item) => item.id === id);
  if (!node || isDiscovered(unlocked, id)) return null;
  if (node.after && !isDiscovered(unlocked, node.after)) return null;
  return node;
}

export type ModSlot = "gun" | "engine" | "plate";

export const MOD_OFFERS: { slot: ModSlot; name: string; coins: number; blurb: string }[] = [
  { slot: "gun", name: "Gun", coins: 40, blurb: "+2 attack" },
  { slot: "engine", name: "Engine", coins: 40, blurb: "+2 move" },
  { slot: "plate", name: "Plate", coins: 40, blurb: "+4 health" },
];

export function modKey(kind: string, slot: ModSlot): string {
  return `${kind}:${slot}`;
}

export function ownsMod(mods: string | undefined, kind: string, slot: ModSlot): boolean {
  return (mods ?? "").split(",").includes(modKey(kind, slot));
}

export function unitBonus(mods: string | undefined, kind: string): { atk: number; move: number; hp: number } {
  return {
    atk: ownsMod(mods, kind, "gun") ? 2 : 0,
    move: ownsMod(mods, kind, "engine") ? 2 : 0,
    hp: ownsMod(mods, kind, "plate") ? 4 : 0,
  };
}

export const MINE_DAMAGE = 8;
export const CAP_OUTPOST = 20;
export const CAP_SPIRE = 30;
export const OPENING_PURSE: [number, number] = [10000, 10000];

export const FACTIONS = [
  { name: "North", player: "Player 1", seat: "Moves first" },
  { name: "South", player: "Player 2", seat: "Same purse as North" },
] as const;

export function damageOf(atk: number, mult: number, hp: number, max: number, dr: number): number {
  if (mult <= 0 || atk <= 0) return 0;
  const frac = 0.55 + 0.45 * (hp / Math.max(1, max));
  const raw = atk * mult * frac * (1 - Math.min(0.55, dr));
  return Math.max(1, Math.round(raw));
}

export function hitChance(opts: {
  kind: string;
  dist: number;
  minRange: number;
  maxRange: number;
  targetAir: boolean;
}): number {
  const acc = ACCURACY[opts.kind] ?? { near: 0.7, far: 0.4, role: "ground" as const };
  const span = Math.max(1, opts.maxRange - opts.minRange);
  const far = Math.min(1, Math.max(0, (opts.dist - opts.minRange) / span));
  let p = acc.near + (acc.far - acc.near) * far;
  if (opts.targetAir && acc.role === "ground") p *= 0.4;
  else if (opts.targetAir && acc.role === "sea") p *= 0.72;
  else if (!opts.targetAir && acc.role === "aa") p *= 0.5;
  return Math.round(Math.min(0.97, Math.max(0.12, p)) * 100) / 100;
}

export function hitBand(kind: string, minRange: number, maxRange: number): string {
  if (maxRange <= 0) return "—";
  const profile = ACCURACY[kind];
  const vsAir = profile?.role === "aa" || profile?.role === "air";
  const near = hitChance({ kind, dist: Math.max(1, minRange), minRange, maxRange, targetAir: vsAir });
  const far = hitChance({ kind, dist: maxRange, minRange, maxRange, targetAir: vsAir });
  const a = Math.round(Math.min(near, far) * 100);
  const b = Math.round(Math.max(near, far) * 100);
  return a === b ? `${a}%` : `${a}–${b}%`;
}

const ACCURACY: Record<string, { near: number; far: number; role: "ground" | "air" | "sea" | "aa" }> = {
  squad: { near: 0.72, far: 0.28, role: "ground" },
  marksman: { near: 0.97, far: 0.88, role: "ground" },
  bullhead: { near: 0.7, far: 0.4, role: "ground" },
  tank: { near: 0.92, far: 0.78, role: "ground" },
  pike: { near: 0.9, far: 0.74, role: "ground" },
  aagun: { near: 0.7, far: 0.38, role: "aa" },
  lobber: { near: 0.4, far: 0.18, role: "ground" },
  rotor: { near: 0.66, far: 0.38, role: "air" },
  fighter: { near: 0.8, far: 0.62, role: "air" },
  bomber: { near: 0.5, far: 0.28, role: "ground" },
  ship: { near: 0.7, far: 0.4, role: "sea" },
  destroyer: { near: 0.78, far: 0.55, role: "sea" },
  ram: { near: 0.34, far: 0.14, role: "ground" },
  turret: { near: 0.72, far: 0.36, role: "ground" },
  bunker: { near: 0.6, far: 0.32, role: "ground" },
  aa: { near: 0.64, far: 0.3, role: "aa" },
  salvo: { near: 0.38, far: 0.16, role: "ground" },
  heavy: { near: 0.9, far: 0.7, role: "ground" },
  sam: { near: 0.82, far: 0.48, role: "aa" },
  drone: { near: 0.58, far: 0.34, role: "air" },
  sub: { near: 0.84, far: 0.58, role: "sea" },
  spotter: { near: 0.9, far: 0.72, role: "ground" },
  grenade: { near: 0.7, far: 0.45, role: "ground" },
  scorch: { near: 0.62, far: 0.4, role: "ground" },
  field: { near: 0.48, far: 0.22, role: "ground" },
  siege: { near: 0.36, far: 0.14, role: "ground" },
  sapper: { near: 0.7, far: 0.4, role: "ground" },
  scout: { near: 0.68, far: 0.36, role: "ground" },
  hunter: { near: 0.9, far: 0.7, role: "ground" },
  wrecker: { near: 0.86, far: 0.64, role: "ground" },
  monarch: { near: 0.9, far: 0.72, role: "ground" },
  raider: { near: 0.74, far: 0.48, role: "sea" },
  lancer: { near: 0.8, far: 0.5, role: "sea" },
  lurker: { near: 0.86, far: 0.6, role: "sea" },
  dread: { near: 0.66, far: 0.32, role: "sea" },
  thunder: { near: 0.68, far: 0.4, role: "air" },
  eye: { near: 0.55, far: 0.3, role: "air" },
  vault: { near: 0.48, far: 0.24, role: "ground" },
  ace: { near: 0.86, far: 0.68, role: "air" },
  breacher: { near: 0.68, far: 0.42, role: "ground" },
  demo: { near: 0.64, far: 0.36, role: "ground" },
  pioneer: { near: 0.7, far: 0.4, role: "ground" },
  engineer: { near: 0.66, far: 0.34, role: "ground" },
  atgm: { near: 0.84, far: 0.55, role: "ground" },
  ambush: { near: 0.92, far: 0.74, role: "ground" },
  dozer: { near: 0.8, far: 0.5, role: "ground" },
  spg: { near: 0.46, far: 0.2, role: "ground" },
  command: { near: 0.88, far: 0.68, role: "ground" },
  spear: { near: 0.9, far: 0.72, role: "ground" },
  monitor: { near: 0.6, far: 0.28, role: "sea" },
  battle: { near: 0.64, far: 0.32, role: "sea" },
  asw: { near: 0.82, far: 0.55, role: "sea" },
  escort: { near: 0.74, far: 0.42, role: "aa" },
  cruise: { near: 0.5, far: 0.22, role: "sea" },
  wolf: { near: 0.88, far: 0.62, role: "sea" },
  armed: { near: 0.6, far: 0.34, role: "air" },
  radarplane: { near: 0.5, far: 0.3, role: "air" },
  night: { near: 0.84, far: 0.66, role: "air" },
  dogfight: { near: 0.88, far: 0.7, role: "air" },
  strategic: { near: 0.46, far: 0.22, role: "ground" },
  pathfinder: { near: 0.52, far: 0.28, role: "ground" },
  heavygun: { near: 0.5, far: 0.24, role: "ground" },
  mlrs: { near: 0.34, far: 0.14, role: "ground" },
  pillbox: { near: 0.7, far: 0.4, role: "ground" },
  casemate: { near: 0.55, far: 0.26, role: "ground" },
  samsite: { near: 0.8, far: 0.42, role: "aa" },
  point: { near: 0.72, far: 0.38, role: "aa" },
  nest: { near: 0.64, far: 0.34, role: "ground" },
  net: { near: 0.7, far: 0.36, role: "aa" },
  pit: { near: 0.4, far: 0.16, role: "ground" },
  flak: { near: 0.66, far: 0.32, role: "aa" },
  dmr: { near: 0.98, far: 0.9, role: "ground" },
  sharp: { near: 0.98, far: 0.92, role: "ground" },
  longshot: { near: 0.99, far: 0.94, role: "ground" },
  phantom: { near: 0.99, far: 0.96, role: "ground" },
  counter: { near: 0.94, far: 0.82, role: "ground" },
  overwatch: { near: 0.95, far: 0.84, role: "ground" },
  stalker: { near: 0.96, far: 0.86, role: "ground" },
  materiel: { near: 0.9, far: 0.74, role: "ground" },
  fifty: { near: 0.88, far: 0.7, role: "ground" },
  sabot: { near: 0.86, far: 0.68, role: "ground" },
  hull: { near: 0.62, far: 0.4, role: "ground" },
  breachlay: { near: 0.64, far: 0.42, role: "ground" },
  siegelay: { near: 0.66, far: 0.44, role: "ground" },
  apex: { near: 0.99, far: 0.97, role: "ground" },
  shade: { near: 0.96, far: 0.88, role: "ground" },
  penetrator: { near: 0.86, far: 0.7, role: "ground" },
  superheavy: { near: 0.52, far: 0.26, role: "ground" },
  barrage: { near: 0.36, far: 0.16, role: "ground" },
  skylance: { near: 0.84, far: 0.5, role: "aa" },
  marshal: { near: 0.9, far: 0.74, role: "ground" },
  glaive: { near: 0.92, far: 0.76, role: "ground" },
  flagship: { near: 0.66, far: 0.34, role: "sea" },
  citadel: { near: 0.62, far: 0.3, role: "sea" },
  boomer: { near: 0.52, far: 0.24, role: "sea" },
  killer: { near: 0.9, far: 0.66, role: "sea" },
  spectre: { near: 0.86, far: 0.68, role: "air" },
  raptor: { near: 0.9, far: 0.74, role: "air" },
  arsenal: { near: 0.48, far: 0.24, role: "ground" },
  seamark: { near: 0.54, far: 0.3, role: "ground" },
  fortress: { near: 0.68, far: 0.46, role: "ground" },
  redoubt: { near: 0.72, far: 0.42, role: "ground" },
  coastgun: { near: 0.56, far: 0.28, role: "ground" },
  umbrella: { near: 0.82, far: 0.44, role: "aa" },
  ciws: { near: 0.74, far: 0.4, role: "aa" },
  carrier: { near: 0.7, far: 0.4, role: "sea" },
  aegis: { near: 0.76, far: 0.44, role: "aa" },
  rampart: { near: 0.62, far: 0.3, role: "sea" },
  marlin: { near: 0.9, far: 0.66, role: "sea" },
  bastion: { near: 0.72, far: 0.42, role: "ground" },
  harbor: { near: 0.56, far: 0.28, role: "ground" },
  skyfort: { near: 0.82, far: 0.44, role: "aa" },
  phalanx: { near: 0.74, far: 0.4, role: "aa" },
};
